/**
  Aplicația 6.3: Să se modifice exemplul 6 astfel încât fiecare valoare din
                 tabelă să aibă următoarea semnificație:
                  - bitul 0==1 => literă mică,
                  - bitul 1==1 => literă mare,
                  - bitul 2==1 => cifră.
                 Să se scrie 3 macrouri, ISLOWER, ISUPPER și ISDIGIT care,
                 folosind tabela, să testeze încadrarea argumentului lor
                 în aceste clase de caractere.
*/

#include <stdio.h>

/* Structure and properties of the predefined value table:
  - this table will have precomputed specific value for every number in range
    0-255, so we can easily find out the properties of a byte sized variable (char)
    when looking up its value in the table
  - the best way to build the table is as an 16x16 matrix
  - structure:
      - the table is comprised of 16 rows -> every row generated by LINE(number_of_line)
      - every row is made up of 16 values -> every value is given by VALUE(index)
  - possible values:
    - 1 (0b 0000 0001) - when the char associated with the index is lowercase
    - 2 (0b 0000 0010) - when the char associated with the index is uppercase
    - 4 (0b 0000 0100) - when the char associated with the index is a digit
*/

#define VALUE(v)                                                               \
  (((v) >= 'a' && (v) <= 'z' ? 1 : 0) |                                        \
  ((v) >= 'A' && (v) <= 'Z' ? 2 : 0) |                                         \
  ((v) >= '0' && (v) <= '9' ? 4 : 0))

#define LINE(num) VALUE(16*num+0),VALUE(16*num+1),VALUE(16*num+2),VALUE(16*num+3),	  \
                  VALUE(16*num+4),VALUE(16*num+5),VALUE(16*num+6),VALUE(16*num+7),	  \
                  VALUE(16*num+8),VALUE(16*num+9),VALUE(16*num+10),VALUE(16*num+11),	\
                  VALUE(16*num+12),VALUE(16*num+13),VALUE(16*num+14),VALUE(16*num+15)

const char table [] =
  {
    LINE(0), LINE(1), LINE(2), LINE(3),
    LINE(4), LINE(5), LINE(6), LINE(7),
    LINE(8), LINE(9), LINE(10), LINE(11),
    LINE(12), LINE(13), LINE(14), LINE(15)
  };

#define ISLOWER(c) (table [(c)] & 1) // < tests if the char is lowercase
#define ISUPPER(c) (table [(c)] >> 1 & 1) // < tests if the char is uppercase
#define ISDIGIT(c) (table [(c)] >> 2 & 1) // < tests if the char is a digit

int main()
{
  unsigned char c; // < Must be unsigned, so the range is [0, 255], isntead of
                   //   [-127, 127]
  printf("Enter a character: ");
  c = getchar(); // < No need to use myStdlib.h, because it is only a char
  putchar('\n');
  printf("Character data:\n");
  printf("\t - value: %c\n", c);
  printf("\t - is lowercase: %d\n", ISLOWER(c));
  printf("\t - is uppercase: %d\n", ISUPPER(c));
  printf("\t - is digit: %d\n", ISDIGIT(c));

  return 0;
}
